# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WP_EyQzntKfAqvgEvmMFxpIruQFPpyZr
"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
## Read CSV Excel file
Path=("/content/drive/MyDrive/Colab Notebooks/DATA/data-science-datasets-main/Task 1/worldpopulationdata.csv")
df=pd.read_csv(Path)
print(Path)

## We are checking the top 5
display(df.head(5))

## We are now checking bottom 5
display(df.tail(5))

## Checking the columns of the data
df.columns

df.info()

df.describe()

##Checking missing values
df.isna().sum()

## Check unique values for columns
print(df['Country Name'].unique())
print("\n Total no of unique countries", df['Country Name'].nunique())

print(df['Country Code'].unique())
print("\n Total no of unique country Code", df['Country Code'].nunique())

## Removing Unnecessary Columns:
df.drop(['Series_Name','Country_Name'],axis=1,inplace=True)



print(df.columns)

## Removing Unnecessary Columns:
df.drop(['Series_Code','Country_Code'],axis=1,inplace=True)
display(df.head())

## Reload the data to get the 'Series Code' column back
Path=("/content/drive/MyDrive/Colab Notebooks/DATA/data-science-datasets-main/Task 1/worldpopulationdata.csv")
df=pd.read_csv(Path)

##Extract top 10 countries with respect to total poplution Step 1 filter
total_population_data=df[df['Series Code']=='SP.POP.TOTL']
## Step 2: Sort Data based on the total population for 2022
total_population_sorted = total_population_data.sort_values(by="2022", ascending=False)
## Step 3: Get the Top 10 countries with the Highest total populaton for 2022
total_top_ten__countries=total_population_sorted.head(10)
print("Top ten countries of total population \n")
print(total_top_ten__countries)

##Bar Plot
plt.figure(figsize=(15,6))
plt.subplot(2,2,1)
sns.barplot(x="2022",y="Country Code",data=total_top_ten__countries,palette="coolwarm")
plt.title("Top ten contries of total population (2022)",fontsize=11)
plt.xlabel("total popultion",fontsize=11)
plt.ylabel("country",fontsize=11)
plt.show()

plt.figure(figsize=(15,6))
plt.subplot(2,2,2)
sns.barplot(x="2016",y="Country Code",data=total_top_ten__countries,palette="coolwarm")
plt.title("Top ten contries of total population (2016)",fontsize=11)
plt.xlabel("total popultion",fontsize=11)
plt.ylabel("country",fontsize=11)
plt.show()

##Extraction of bottom 10 countries in respect to total population
total_population_sorted1 = total_population_data.sort_values(by="2022", ascending=True)
total_bottom_ten__countries=total_population_sorted.head(10)
print("Top bottom countries of total population \n")
print(total_bottom_ten__countries)

##Bar Plot
plt.figure(figsize=(15,6))
plt.subplot(2,2,2)
sns.barplot(x="2022",y="Country Code",data=total_bottom_ten__countries,palette="coolwarm")
plt.title("bottom 10 contries of total population (2022)",fontsize=11)
plt.xlabel("total popultion",fontsize=11)
plt.ylabel("country",fontsize=11)
plt.show()

plt.figure(figsize=(15,6))
plt.subplot(2,2,2)
sns.barplot(x="2016",y="Country Code",data=total_bottom_ten__countries,palette="coolwarm")
plt.title("Bottom contries of total population (2016)",fontsize=11)
plt.xlabel("total popultion",fontsize=11)
plt.ylabel("country",fontsize=11)
plt.show()

##extraction of top 10 countries in terms of highest male population step 1 filter male pop
male_population_data = df[df['Series Code'] == 'SP.POP.TOTL.MA.IN']
## Step 2: Sort Data based on the total population for 2022
male_population_sorted = male_population_data.sort_values(by="2022", ascending=False)
## Step 3: Get the Top 10 countries with the Highest total populaton for 2022
male_top_ten__countries=male_population_sorted.head(10)
print("Top ten countries of male population \n")
print(male_top_ten__countries[['Country Code']])

## Top Ten countries with highest female populaions in 2022
female_population_data = df[df['Series Code'] == 'SP.POP.TOTL.FE.IN']
## Step 2: Sort Data based on the total population for 2022
female_population_sorted = female_population_data.sort_values(by="2022", ascending=False)
## Step 3: Get the Top 10 countries with the Highest total populaton for 2022
female_top_ten__countries=female_population_sorted.head(10)
print("Top ten countries of female population \n")
print(female_top_ten__countries[['Country Code']])

## Top Ten countries with highest male and female populaions in 2022
##Bar Plot
plt.figure(figsize=(15,6))
plt.subplot(2,2,2)
sns.barplot(x="2022",y="Country Code",data=male_top_ten__countries,palette="viridis")
plt.title("Top ten conuntries with male population (2022)",fontsize=11)
plt.xlabel("Males popultion",fontsize=11)
plt.ylabel("country",fontsize=11)
plt.show()

plt.figure(figsize=(15,6))
plt.subplot(2,2,2)
sns.barplot(x="2016",y="Country Code",data=female_top_ten__countries,palette="viridis")
plt.title("Top ten conuntries with female population (2022)",fontsize=11)
plt.xlabel("Females popultion",fontsize=11)
plt.ylabel("country",fontsize=11)
plt.show()

##Scatter plot or stacked bar plot top 10 countries with male and females populations
## merge male and female popullation data on 'country code'
merge_data = pd.merge(male_top_ten__countries, female_top_ten__countries, on='Country Code')
merge_data["Total poplutions"] = merge_data["2022_x"] + merge_data["2022_y"]

merged_data.head()

##sort data based on total population in descending order
sort_data = merge_data.sort_values(by="Total poplutions", ascending=False)

## Select the top 10 countries with the highest  total population
top_ten_countries = sort_data.head(10)
plt.figure(figsize=(15,6))
sns.barplot(x="Country Code",y="2022_y",data=top_ten_countries,color="red",label="female population")
sns.barplot(x="Country Code",y="2022_x",data=top_ten_countries,bottom=top_ten_countries["2022_y"],color="Blue",label="Male population")
plt.xlabel("Country")
plt.ylabel("Population")
plt.legend()
plt.xticks(rotation = 45, ha='right')
plt.show()